Updated portfolio pull-request
derrick1451/microverse-portfolio pull request #1
Opened 2022-03-17 12:26 UTC by derrick1451

with the help of linters, HTML, and CSS l have created my portfolio that includes
header elements and a section

2022-03-17 13:29 UTC, sja-thedude requested changes
Hi @derrick1451, This is @sja-thedude your code reviewer.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Professional Readme 👍 
- Good commit messages 👍 

## Required Changes ♻️
- Kindly fix the linter error.
- Make sure to add a descriptive title and summary of the pull request.
- _Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-17 13:29 UTC, sja-thedude commented on index.html
> +        <nav><img src="/images/toggle.png" alt=""></nav>
- [ ] Kindly fix the logo according to the Figma design, it should move more to the left side.
- [ ] Kindly fix the hamburger button, it's not displayed.
- Your design:
<img width="305" alt="Screenshot 2022-03-17 at 4 07 33 PM" src="https://user-images.githubusercontent.com/70269507/158815012-c421e646-286b-48a7-9b48-0d6cd7794fdd.png">

- Figma design:
<img width="246" alt="Screenshot 2022-03-17 at 4 06 31 PM" src="https://user-images.githubusercontent.com/70269507/158815044-e21d30e7-6660-43f6-88a4-132e4ad73816.png">

2022-03-17 13:29 UTC, sja-thedude commented on main.css
> +    background-image: url(/images/header.png);
- Kindly fix the background image, it's not displayed.
Your design:
<img width="306" alt="Screenshot 2022-03-17 at 4 02 36 PM" src="https://user-images.githubusercontent.com/70269507/158815617-75a64820-74f2-4236-9511-65e2bcc8f80e.png">

Figma design:
<img width="246" alt="Screenshot 2022-03-17 at 4 03 40 PM" src="https://user-images.githubusercontent.com/70269507/158815639-bc4e1a78-f5d5-4939-96f4-f1107fc80ecb.png">

2022-03-17 13:29 UTC, sja-thedude commented on index.html
> +            <li><img src="/images/fingers.png" alt="thumbsup"></li>
- [ ] Kindly make sure that each `li` icon has a link `a tag`.

2022-03-17 13:29 UTC, sja-thedude commented on index.html
> +        </ul>
- [ ] Kindly make sure your social links are displayed properly on the page.
- Your design:
<img width="297" alt="Screenshot 2022-03-17 at 4 07 18 PM" src="https://user-images.githubusercontent.com/70269507/158816733-2c00ed72-698b-4c06-85b7-5a862d595845.png">

- Figma design:
<img width="245" alt="Screenshot 2022-03-17 at 4 19 40 PM" src="https://user-images.githubusercontent.com/70269507/158817129-963ef89b-fde3-4a12-b043-55142b162099.png">

2022-03-17 13:29 UTC, sja-thedude commented on main.css
> +}
- [ ] Make sure to follow the spacing, font family and font size according to the Figma design. Try to replicate the design as much as possible.
- Your design:
<img width="306" alt="Screenshot 2022-03-17 at 4 02 36 PM" src="https://user-images.githubusercontent.com/70269507/158817882-7e54f8d9-1566-4128-b4f8-2b5d2fdcfcb9.png">

- Figma design:
<img width="246" alt="Screenshot 2022-03-17 at 4 03 40 PM" src="https://user-images.githubusercontent.com/70269507/158817921-0ef58546-8e09-440e-80cb-3ad3eaa89315.png">

2022-03-18 00:19 UTC, Donard97 requested changes
Hi @derrick1451 , 👋  
    
_Great work on making the changes requested by a previous reviewer 👏 💯_ 

You've done well implementing some of the requested changes, but there are still some which aren't addressed yet. 💪 

![giphy (5)](https://user-images.githubusercontent.com/74506933/158914255-c412fcfa-dc99-402d-9023-99e21aab87c9.gif)


## Highlights 🏁 

- There is no linter error ✔️ 
- Gitflow is used correctly ✔️ 
- PR is descriptive ✔️ 
    
## Required Changes ♻️

- [ ] Please check the comments under the review._
    
## Optional suggestions

- [OPTIONAL] I suggest you in the future to give more meaningful names to the branches for example you have to name in base what you will do on that branch. Keep shining 💪 
    
 _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
    
**Cheers and Happy coding!👏👏👏**
    
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.
    
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
    
------
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
 ```

2022-03-18 00:19 UTC, Donard97 commented on main.css
> +  background-image: url(/images/Header\ bg@2x.png);
- [ ] You did an amazing job implementing requested changes from the other reviewer but please stick as much as you can to the [Figma design](). Keep rocking 💪 

Here you have a screenshot from your project:

![image](https://user-images.githubusercontent.com/74506933/158913628-de7f9598-c664-4f38-a8c5-6be002d4ab17.png)

Here you have a screenshot from the design:

![image](https://user-images.githubusercontent.com/74506933/158913807-2eb1f232-57d5-48a8-a84c-6351f3b4d4ed.png)

2022-03-18 00:19 UTC, Donard97 commented on README.md
> +**Modify this file to match your project, remove sections that don't apply. For example: delete the testing section if the currect project doesn't require testing.** -->
- [OPTIONAL] Kindly uncomment the getting start section and please let us know how to clone, setup, and run your project and please delete the unused section. Keep coding 💪

2022-03-18 12:58 UTC, BenMukebo approved these changes
<h1>Status: Approve  :champagne:  :+1: :confetti_ball: 

## *** Hi @derrick1451 *** , 

<img src="https://media2.giphy.com/media/DBGyPSFkfuyJDMl4cZ/giphy.gif"/>

### **Congratulations! 🎉 Project Approved ✅**

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 


### To Highlight :1st_place_medal: 
- Your Pull Request has a proper title and description. ✔️  
- No Linter errors :heavy_check_mark: 
- Your Design looks awesome, keep rocking :rocket: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏💻  

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @BenMukebo ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-18 13:02 UTC, merged