module1:portfolio
derrick1451/microverse-portfolio pull request #2
Opened 2022-03-19 20:16 UTC by derrick1451

module1: portfolio clone
in this milestone, l have created the work section of my portfolio which includes
1, HTML files that contain the whole structure of my page
2, linter files to flag errors in my code
3, CSS files for styling my pages

2022-03-19 21:14 UTC, Gambit142 requested changes
Hi @derrick1451 👋, 

Good job so far!

### Highlights
- All linters checks passed ✔️ 
- Good pull request description ✔️ 
- Use of Figma fonts and colors for template chosen ✔️ 
 
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- You can also consider removing the headers which have no details in your `README.md` file

![image](https://user-images.githubusercontent.com/77106962/159138436-945d8892-0064-433a-8838-76576c556afb.png)

- It would be nice to include instructions in the _**Getting Started/Setup**_ section for cloning your repo when a person visits your site. You can take a peep at this [repo](https://github.com/Gambit142/To-Do-List-Project) to have an idea of how to go about it.


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-03-19 21:14 UTC, Gambit142 commented on index.html
> +
- [ ] Nice work implementing the **_Projects_** section, but you did not implement the **_About myself_** section. Kindly implement that, so that you can scale through this milestone. 👍 

### About Myself Section

![image](https://user-images.githubusercontent.com/77106962/159138234-8a104d58-bbfc-409c-aaf1-05fba619e2dd.png)

2022-03-19 22:50 UTC, AnselemOdims requested changes
### Hi @derrick1451, 
Good job implementing some of the changes requested by the previous reviewer.

## Required Changes ♻️
- [ ] Please also check inline comments under the review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Please leave any questions or comments in the PR if you have any doubts or unclarity! You can tag me using @AnselemOdims for a quicker response

**_Note: Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-03-19 22:50 UTC, AnselemOdims commented on index.html
> +
- [ ] As already requested by the previous reviewer, this milestone requires that you complete both the `works` and the `about` section. At the moment, you only have the `works` section. Please kindly add the `about` section to complete this milestone.

2022-03-24 09:28 UTC, Deepakdanger approved these changes
Hi @derrick1451, 

### Status: Approved ✔️

Your project is complete!  There is nothing else to say other than... it's time to merge it  🚢 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-24 09:57 UTC, merged